image: gitpod/workspace-python

tasks:
  - name: Install Libraries and run simple Flask app
    init: pip install -r requirements.txt
    command: python simple_server.py

ports:
  - name: Server
    description: Port 8000 for the HTTP listener
    port: 8000

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
